'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { supabase } from '../../lib/supabase';

export default function Admin() {
  const [data, setData] = useState(null), [error, setError] = useState('');
  useEffect(() => { (async () => { const { data: { session } } = await supabase.auth.getSession(); const response = await fetch('/api/progress', { headers: { Authorization: `Bearer ${session?.access_token || ''}` } }); const result = await response.json(); if (!response.ok) setError(result.error); else setData(result); })(); }, []);
  if (error) return <main className="admin-page"><p className="notice notice-error">{error}</p><Link className="back-link back-button" href="/">Back to library</Link></main>;
  if (!data) return <main className="admin-page"><header className="author-header"><div><span className="eyebrow skeleton-line admin-skeleton-label" /><h1 className="skeleton-line admin-skeleton-title" /><div className="skeleton-line admin-skeleton-copy" /></div><div className="admin-links"><span className="skeleton-line admin-skeleton-button" /><span className="skeleton-line admin-skeleton-button small" /></div></header><div className="admin-stats"><div className="skeleton-card admin-stat-skeleton" /><div className="skeleton-card admin-stat-skeleton" /><div className="skeleton-card admin-stat-skeleton" /></div><section className="admin-section"><div className="section-heading"><span className="skeleton-line admin-section-heading" /></div><div className="admin-table"><div className="skeleton-line admin-row-skeleton" /><div className="skeleton-line admin-row-skeleton" /><div className="skeleton-line admin-row-skeleton" /></div></section><section className="admin-section"><div className="section-heading"><span className="skeleton-line admin-section-heading" /></div><div className="admin-table"><div className="skeleton-line admin-row-skeleton" /><div className="skeleton-line admin-row-skeleton" /><div className="skeleton-line admin-row-skeleton" /></div></section></main>;

  const learnerRows = data.learners || [];
  const exerciseProgressRows = data.exerciseProgress || [];

  return <main className="admin-page"><header className="author-header"><div><span className="eyebrow">Admin overview</span><h1>Learning progress</h1><p>See who is practicing, how often, and which exercises are available.</p></div><div className="admin-links"><Link className="primary-button" href="/add">Add exercise</Link><Link className="back-link back-button" href="/">Library</Link></div></header><div className="admin-stats"><div><strong>{data.learners.length}</strong><span>Learners</span></div><div><strong>{data.attempts.length}</strong><span>Total attempts</span></div><div><strong>{data.exercises.length}</strong><span>Exercises</span></div></div><section className="admin-section"><div className="section-heading"><h2>Learner progress</h2></div>{learnerRows.length ? <div className="admin-table">{learnerRows.map(learner => <div className="admin-row" key={learner.id}><strong>{learner.full_name || 'Learner'}</strong><span>{learner.attempts} exercises attempted</span><span>{learner.average}% average</span></div>)}</div> : <div className="section-empty-state"><div className="empty-state-illustration" aria-hidden="true">📈</div><strong>No learner activity yet</strong><p>As learners practice, their progress and averages will appear here.</p></div>}</section><section className="admin-section"><div className="section-heading"><h2>Exercise progress</h2></div>{exerciseProgressRows.length ? <div className="admin-table">{exerciseProgressRows.map(exercise => <div className="admin-row" key={exercise.exercise_id}><strong>{exercise.title}</strong><span>{exercise.attempt_count} attempts</span><span>{exercise.learners.length ? exercise.learners.join(', ') : 'No learners yet'}</span></div>)}</div> : <div className="section-empty-state"><div className="empty-state-illustration" aria-hidden="true">🎯</div><strong>No exercise attempts yet</strong><p>Once exercises are completed, you will see how often they were attempted and by whom.</p></div>}</section></main>;
}
